(function () {
    'use strict';
    var ENDPOINT = 'https://xwscxatdfekbbxuqsbcj.supabase.co/functions/v1/cms';
    var AUTH_KEY = 'futurify_cms_admin_token';
    var ZONE_ATTR = 'data-cms-custom-sections';
    var EDITABLE = 'h1,h2,h3,h4,h5,h6,p,li,a,button,span,strong,em,blockquote,img';
    var state = {}, activeEditor;
    function pageKey() { return (location.pathname.split('/').pop() || 'index.html').toLowerCase(); }
    function token() { return sessionStorage.getItem(AUTH_KEY); }
    function page() { var key = pageKey(); if (!state[key]) state[key] = { nodes: {}, customSections: {} }; state[key].nodes ||= {}; state[key].customSections ||= {}; return state[key]; }
    function path(el) { if (el.id) return '#' + el.id; var parts = []; while (el && el.nodeType === 1 && el !== document.body) { var i = 1, sibling = el; while ((sibling = sibling.previousElementSibling)) if (sibling.tagName === el.tagName) i++; parts.unshift(el.tagName.toLowerCase() + ':nth-of-type(' + i + ')'); el = el.parentElement; } return parts.join('>'); }
    function apply(el, value) { if (!value) return; el.style.display = value.hidden ? 'none' : ''; if (value.html != null && el.tagName !== 'IMG') el.innerHTML = value.html; if (value.href && el.tagName === 'A') el.href = value.href; if (value.src && el.tagName === 'IMG') el.src = value.src; if (value.alt != null && el.tagName === 'IMG') el.alt = value.alt; }
    function applyAll() { var current = page(); document.querySelectorAll(EDITABLE).forEach(function (el) { apply(el, current.nodes[path(el)]); }); document.querySelectorAll('[' + ZONE_ATTR + ']').forEach(function (zone) { var html = current.customSections[zone.getAttribute(ZONE_ATTR)]; if (html != null) zone.innerHTML = html; }); }
    function api(method, body) { var headers = { 'Content-Type': 'application/json' }; if (token()) headers.Authorization = 'Bearer ' + token(); return fetch(ENDPOINT, { method: method, headers: headers, body: body && JSON.stringify(body) }).then(function (res) { return res.json().then(function (data) { if (!res.ok) throw Error(data.error || 'CMS request failed.'); return data; }); }); }
    function save() { return api('POST', { action: 'save', pageKey: pageKey(), content: page() }); }
    function esc(value) { return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
    function close() { if (activeEditor) activeEditor.remove(); activeEditor = null; }
    function edit(el) { close(); var key = path(el), prior = page().nodes[key] || {}, image = el.tagName === 'IMG', link = el.tagName === 'A'; var modal = document.createElement('div'); modal.className = 'cms-editor'; modal.innerHTML = '<div class="cms-editor-card"><div class="cms-editor-head"><strong>Admin Editor</strong><button data-close>&times;</button></div>' + (image ? '<label>Image URL</label><input data-src value="' + esc(prior.src || el.getAttribute('src') || '') + '"><label>Alt text</label><input data-alt value="' + esc(prior.alt || el.alt || '') + '">' : '<label>Content</label><textarea data-html>' + esc(prior.html || el.innerHTML) + '</textarea>') + (link ? '<label>Link URL</label><input data-href value="' + esc(prior.href || el.getAttribute('href') || '') + '">' : '') + '<label class="cms-checkbox"><input type="checkbox" data-hidden ' + (prior.hidden ? 'checked' : '') + '> Hide this element</label><div class="cms-editor-actions"><button data-reset>Reset</button><button data-save>Save</button></div></div>'; document.body.appendChild(modal); activeEditor = modal; modal.querySelector('[data-close]').onclick = close; modal.onclick = function (e) { if (e.target === modal) close(); }; modal.querySelector('[data-save]').onclick = function () { var next = { hidden: modal.querySelector('[data-hidden]').checked }; if (image) { next.src = modal.querySelector('[data-src]').value.trim(); next.alt = modal.querySelector('[data-alt]').value.trim(); } else next.html = modal.querySelector('[data-html]').value; if (link) next.href = modal.querySelector('[data-href]').value.trim(); page().nodes[key] = next; apply(el, next); save().then(close).catch(function (e) { alert(e.message); }); }; modal.querySelector('[data-reset]').onclick = function () { delete page().nodes[key]; save().then(function () { location.reload(); }).catch(function (e) { alert(e.message); }); }; }
    function toolbar() { var bar = document.createElement('div'); bar.className = 'cms-toolbar'; bar.innerHTML = '<button data-add>Add Section</button><button data-zone>Edit Section Area</button><button data-clear>Reset Page</button><button data-logout>Logout</button>'; document.body.appendChild(bar); bar.querySelector('[data-logout]').onclick = function () { sessionStorage.removeItem(AUTH_KEY); location.href = 'admin.html'; }; bar.querySelector('[data-clear]').onclick = function () { if (confirm('Reset all saved changes on this page?')) api('POST', { action: 'reset', pageKey: pageKey() }).then(function () { location.reload(); }).catch(function (e) { alert(e.message); }); }; function sectionEditor(add) { var zone = document.querySelector('[' + ZONE_ATTR + ']'); if (!zone) return alert('No custom section area is available on this page.'); var next = prompt(add ? 'Paste section HTML:' : 'Edit the custom section HTML:', add ? '<section class="cms-section"><h2>New Section</h2><p>Edit this section content.</p></section>' : zone.innerHTML); if (next == null || !next) return; if (add) zone.insertAdjacentHTML('beforeend', next); else zone.innerHTML = next; page().customSections[zone.getAttribute(ZONE_ATTR)] = zone.innerHTML; save().catch(function (e) { alert(e.message); }); } bar.querySelector('[data-add]').onclick = function () { sectionEditor(true); }; bar.querySelector('[data-zone]').onclick = function () { sectionEditor(false); }; }
    function styles() { var style = document.createElement('style'); style.textContent = '.cms-toolbar{position:fixed;right:18px;bottom:18px;z-index:400000;display:flex;gap:10px;flex-wrap:wrap;padding:12px;background:rgba(6,6,6,.92);border:1px solid rgba(242,237,229,.15);backdrop-filter:blur(14px)}.cms-toolbar button{background:#c8f135;color:#060606;border:none;padding:10px 14px;font:700 12px Syne,sans-serif;cursor:pointer}.cms-editor{position:fixed;inset:0;z-index:400100;background:rgba(6,6,6,.82);display:flex;align-items:center;justify-content:center;padding:20px}.cms-editor-card{width:min(720px,100%);background:#060606;border:1px solid rgba(242,237,229,.16);padding:20px;display:flex;flex-direction:column;gap:10px;color:#f2ede5}.cms-editor-head{display:flex;align-items:center;justify-content:space-between}.cms-editor-head button{background:none;border:none;color:#f2ede5;font-size:28px;cursor:pointer}.cms-editor textarea,.cms-editor input{width:100%;background:#111;border:1px solid rgba(242,237,229,.18);color:#f2ede5;padding:12px;font:400 13px "DM Mono",monospace}.cms-editor textarea{min-height:220px;resize:vertical}.cms-editor label{font:700 11px "DM Mono",monospace;letter-spacing:.08em;text-transform:uppercase;color:rgba(242,237,229,.72)}.cms-editor-actions{display:flex;gap:10px;justify-content:flex-end}.cms-editor-actions button{padding:10px 14px;border:none;cursor:pointer;font:700 12px Syne,sans-serif}.cms-editor-actions [data-reset]{background:#1b1b1b;color:#f2ede5;border:1px solid rgba(242,237,229,.16)}.cms-editor-actions [data-save]{background:#c8f135;color:#060606}.cms-checkbox{display:flex;align-items:center;gap:10px}.cms-checkbox input{width:auto}.cms-editable{outline:1px dashed rgba(200,241,53,.25);outline-offset:4px;cursor:pointer!important}@media(max-width:700px){.cms-toolbar{left:12px;right:12px;bottom:12px}.cms-toolbar button{flex:1 1 140px}}'; document.head.appendChild(style); }
    function enable() { if (!token() || /\/admin\.html$/i.test(location.pathname)) return; styles(); toolbar(); document.querySelectorAll(EDITABLE).forEach(function (el) { if (el.closest('.cms-toolbar,.cms-editor') || el.hasAttribute('data-cms-ignore')) return; el.classList.add('cms-editable'); el.onclick = function (e) { e.preventDefault(); e.stopPropagation(); edit(el); }; }); }
    function init() { if (/\/admin\.html$/i.test(location.pathname)) return; api('GET').then(function (data) { state = data.pages || {}; applyAll(); enable(); }).catch(function () { applyAll(); enable(); }); }
    window.FuturifyCMS = { login: function (email, password) { return api('POST', { action: 'login', email: email, password: password }).then(function (data) { sessionStorage.setItem(AUTH_KEY, data.token); }); } };
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init); else init();
})();
